#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
title: Ian Burke's ENGL 350 Blog
# Short bio or description (displayed in the header)
description: A Blog to be used for the Digital Humanities class. My name is Ian Burke, I am a senior writing major and film studies minor at Christopher Newport University.

#
# !! DON'T EDIT BELOW THIS MESSAGE
#
# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
