---
layout: post
title: Review of Shelley-Godwin Archive Project
--- 

The Shelley-Godwin Archive is a digital archival effort to gather and digitize the manuscripts of Mary Wollstonecraft Shelley’s family: Mary Shelley, Percy Bysshe Shelley, Peter Godwin, and Mary Wollstonecraft. The handwritten manuscripts of these authors are scattered through several different collections across continents, but now academic scholars have a centralized digital archive to refer to as a source. A unique collection from the single most influential family of writers in the Western Literary canon, the archive chronicles their lives, thoughts, and the development of several works that have become cemented in the literary consciousness of the Western world.  

 
The archive itself is the result of a continuing partnership between the Maryland Institute for Technology in the Humanities and the New York Public Library. Contributions to their collection also come from across the Atlantic out of Oxford’s Bodleian Library, Huntington Library, British Library, Houghton Library, and the Victoria and Albert Museum. The entirety of this collection contains over 90% of all manuscripts relevant to documenting the bibliographical development of “England’s First Family of Writers.” An epithet coined by author Julie A. Carson, the family including Mary Shelley’s husband would work almost exclusively alone on works that included _A Vindication of the Rights of Women_, some of the most influential and beautiful poetry in the English language, as well as Mary Shelley’s _Frankenstein, or the Modern Prometheus_, a haunting story that has achieved mythic status while being the first real science fiction story in the English canon.  

 
The technological infrastructure of the archive is comprised of data models and standards set by **Shared Canvas**; a model centered around the concept of annotation to associate media files with an artifact represented by an abstract canvas, enabling anyone with internet access to engage in discourse on and reuse the archival materials and digital editions. The Shared Canvas also seeks to break down the walls which conventionally enclosed digital archives of this nature. “The Linked open data or content is published and licensed so that “anyone is free to use, reuse, and redistribute it”, but must include a universal resource identifier (URI) that can be shared between archives, scholarly projects, etc. As far as the digitizing and encoding of the actual documents into the archive, the Shelley-Godwin project uses the **Text Encoding Initiative** (TEI) standards for encoding texts to be used in the academic community. Fields ranging from linguistics, musicology, and history use this initiative to make text and scholarship around text machine-readable. This digital manuscript archive is actually one of the earlier DH projects to adopt the TEI module called _“Module for Transcription of Primary Resources”_, allowing an editor to describe a “written surface by identifying zones of writing and their relationships”. The appearance of text on the page of a manuscript and identifying revisions by the author or other contributors to the work, which is important in a family of writers who sometimes influenced or outright contributed to one another’s works. The encoded transcription has three levels of categorization: red indicating that a transcription is unavailable, yellow indicates a basic transcription exists but is not vetted, and green indicates that the transcription is complete and verified.  

 
The current staff of the project includes six individual editors, and the requisite set-up required several editors and managers to find and encode manuscripts into the digital archive. Contributors to the encoding process came from universities such as the University of Maryland and University of Virginia, all under the supervision of a professor. Serving on the advisory board are technologists and scholars distinguished in their respective fields from colleges and universities in the Ivy League and other colleges in America, to Canadian and British universities as well. All helping to vet the documents and supervise the encoded transcription process for the betterment of the archive. The staff’s backgrounds also serve as a marker for who the archive caters to towards: academia. Wollstonecraft, Godwin, and the Shelleys influenced Western literary tradition and the body of academic work discussing them is large and ever-expanding. But original documents such as manuscripts and works in progress are not easy to get a hold of, making the process of academic research a difficult and drawn out process of waiting for a document from Britain and waiting for another out of Harvard. With the archive, academic scholars and independent researchers will have a central hub for primary research on England’s First Family of writers.  

 
The large body of work and sources this project pulls from makes it difficult for any researcher to get a comprehensive image of the development of this family, but the archive is actively working towards that goal with its growing body of digitized manuscripts. Manuscripts for Percy Shelley’s poetry, pages from early drafts of _Frankenstein_, annotated pages from Wollstonecraft’s essays and Godwin’s manifestos, all contribute to the vision of England’s First Family. The encoding process is also exceeding helpful and comprehensive due to its feature of segmenting text written by, for example, Mary Shelley or Percy Shelley on the drafts of _Frankenstein_. A single check of a box on the page and all the viewer sees is either Mary Shelley’s draft and edits, or Percy Shelley’s notes within the margins of the text. Overall, the archive’s deft application of transcription encoding coupled with the Herculean networking efforts needed to establish such a digital archive mark it as a superb example of primary research and information gathering.
